.TH olive-editor 1 "December 21 2018"
.SH NAME
olive-editor \- video editor
.SH SYNOPSIS
.B olive-editor
.RI "files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B olive-editor
command.
.PP
\fBolive-editor\fP is a free non-linear video editor aiming to provide a fully-featured
alternative to high-end professional video editing software.
.SH SEE ALSO
.BR shotcut (1).
.br
